Repository Mbed-TLS/mbedtls-docs, pull requests merged in 2022-08, with the labels that each got.

#35 Update mbedtls-security-advisory-2022-07.md
  security-advisories/advisories/mbedtls-security-advisory-2022-07.md
Labels: bug, size-s, priority-medium

#31 Add / remove syntax highlighting from code blocks where necessary
  reviews/review_guidelines.md
  security-advisories/advisories/polarssl-security-advisory-2011-01.md
  security-advisories/advisories/polarssl-security-advisory-2012-01.md
  security-advisories/advisories/polarssl-security-advisory-2013-03.md
  security-advisories/advisories/polarssl-security-advisory-2013-04.md
  security-advisories/advisories/polarssl-security-advisory-2014-02.md
  security-advisories/advisories/polarssl-security-advisory-2014-04.md
Labels: enhancement, size-s, priority-medium

#40 Remove the .html extensions from page URLs
  .readthedocs.yaml
Labels: enhancement, needs-review, needs-reviewer, size-s, priority-medium

#41 Move kb article to match old website layout
  kb/how-to/controlling_package_size.md
Labels: bug, needs-review, needs-reviewer, size-s, priority-medium

#36 Convert advisory list to auto-generated toctree
  security-advisories/advisories/mbedtls-security-advisory-2015-01.md
  security-advisories/advisories/mbedtls-security-advisory-2017-01.md
  security-advisories/advisories/mbedtls-security-advisory-2018-01.md
  security-advisories/advisories/mbedtls-security-advisory-2018-02.md
  security-advisories/advisories/mbedtls-security-advisory-2018-03.md
  security-advisories/advisories/mbedtls-security-advisory-2019-10.md
  security-advisories/advisories/mbedtls-security-advisory-2019-12.md
  security-advisories/advisories/mbedtls-security-advisory-2020-02.md
  security-advisories/advisories/mbedtls-security-advisory-2020-04.md
  security-advisories/advisories/mbedtls-security-advisory-2020-09-3.md
  security-advisories/advisories/polarssl-security-advisory-2011-01.md
  security-advisories/advisories/polarssl-security-advisory-2011-02.md
  security-advisories/advisories/polarssl-security-advisory-2012-01.md
  security-advisories/advisories/polarssl-security-advisory-2013-01.md
  security-advisories/advisories/polarssl-security-advisory-2013-02.md
  security-advisories/advisories/polarssl-security-advisory-2013-03.md
  security-advisories/advisories/polarssl-security-advisory-2013-04.md
  security-advisories/advisories/polarssl-security-advisory-2013-05.md
  security-advisories/advisories/polarssl-security-advisory-2014-04.md
  security-advisories/security-advisories.md
Labels: bug, size-s, priority-medium

#37 Add review-priorities.md to the toctree
  index.md
  reviews/index.md
Labels: bug, size-s, priority-medium

#38 Fix warnings about non-consecutive heading levels
  reviews/review-priorities.md
  reviews/review_guidelines.md
Labels: bug, size-s, priority-medium

#42 Restore content of security advisory 2017-01
  security-advisories/advisories/mbedtls-security-advisory-2017-01.md
Labels: bug, size-s, priority-medium

#43 Move security advisories to match old website
  index.md
  tech-updates/security-advisories/index.md
  tech-updates/security-advisories/mbedtls-security-advisory-2015-01.md
  tech-updates/security-advisories/mbedtls-security-advisory-2017-01.md
  tech-updates/security-advisories/mbedtls-security-advisory-2017-02.md
  tech-updates/security-advisories/mbedtls-security-advisory-2018-01.md
  tech-updates/security-advisories/mbedtls-security-advisory-2018-02.md
  tech-updates/security-advisories/mbedtls-security-advisory-2018-03.md
  tech-updates/security-advisories/mbedtls-security-advisory-2019-10.md
  tech-updates/security-advisories/mbedtls-security-advisory-2019-12.md
  tech-updates/security-advisories/mbedtls-security-advisory-2020-02.md
  tech-updates/security-advisories/mbedtls-security-advisory-2020-04.md
  tech-updates/security-advisories/mbedtls-security-advisory-2020-07.md
  tech-updates/security-advisories/mbedtls-security-advisory-2020-09-1.md
  tech-updates/security-advisories/mbedtls-security-advisory-2020-09-2.md
  tech-updates/security-advisories/mbedtls-security-advisory-2020-09-3.md
  tech-updates/security-advisories/mbedtls-security-advisory-2021-07-1.md
  tech-updates/security-advisories/mbedtls-security-advisory-2021-07-2.md
  tech-updates/security-advisories/mbedtls-security-advisory-2021-12.md
  tech-updates/security-advisories/mbedtls-security-advisory-2022-07.md
  tech-updates/security-advisories/polarssl-security-advisory-2011-01.md
  tech-updates/security-advisories/polarssl-security-advisory-2011-02.md
  tech-updates/security-advisories/polarssl-security-advisory-2012-01.md
  tech-updates/security-advisories/polarssl-security-advisory-2013-01.md
  tech-updates/security-advisories/polarssl-security-advisory-2013-02.md
  tech-updates/security-advisories/polarssl-security-advisory-2013-03.md
  tech-updates/security-advisories/polarssl-security-advisory-2013-04.md
  tech-updates/security-advisories/polarssl-security-advisory-2013-05.md
  tech-updates/security-advisories/polarssl-security-advisory-2014-01.md
  tech-updates/security-advisories/polarssl-security-advisory-2014-02.md
  tech-updates/security-advisories/polarssl-security-advisory-2014-03-poodle-attack-on-ssl-v3.md
  tech-updates/security-advisories/polarssl-security-advisory-2014-04.md
Labels: enhancement, needs-review, needs-reviewer, size-s, priority-medium

#44 Replace links to tls.mbed.org with internal references
  architecture/proposed/long-term-plans.md
  kb/compiling-and-building/compile-mbedtls-to-a-static-library-in-eclipse-cdt.md
  kb/compiling-and-building/compiling-mbedtls-in-mingw.md
  kb/compiling-and-building/how-do-i-configure-mbedtls.md
  kb/compiling-and-building/mbedtls-failed-to-compile.md
  kb/compiling-and-building/setup-eclipse-cdt-environment-on-windows.md
  kb/compiling-and-building/using-mbedtls-in-microsoft-visual-studio-2015.md
  kb/cryptography/elliptic-curve-performance-nist-vs-brainpool.md
  kb/cryptography/ephemeral-diffie-hellman.md
  kb/cryptography/providing-diffie-hellman-or-dhm-parameters.md
  kb/cryptography/rsa-key-pair-generator.md
  kb/cryptography/use-external-rsa-private-key.md
  kb/development/entropy-collection-and-random-generation-in-threaded-environment.md
  kb/development/generating-mbedtls-api-documentation-locally.md
  kb/development/hw_acc_guidelines.md
  kb/development/mbedtls-coding-standards.md
  kb/development/sample_applications.md
  kb/development/thread-safety-and-multi-threading.md
  kb/development/what-external-dependencies-does-mbedtls-rely-on.md
  kb/generic/ftp-folder-for-automatic-downloads.md
  kb/generic/mbedtls-philosophy.md
  kb/generic/what-tests-and-checks-are-run-for-polarssl.md
  kb/how-to/add-a-random-generator.md
  kb/how-to/add-entropy-sources-to-entropy-pool.md
  kb/how-to/code-size.md
  kb/how-to/controlling_package_size.md
  kb/how-to/dtls-tutorial.md
  kb/how-to/encrypt-and-decrypt-with-rsa.md
  kb/how-to/encrypt-with-aes-cbc.md
  kb/how-to/generate-a-certificate-request-csr.md
  kb/how-to/generate-a-self-signed-certificate.md
  kb/how-to/generate-an-aes-key.md
  kb/how-to/how-do-i-port-mbed-tls-to-a-new-environment-OS.md
  kb/how-to/how-do-i-tune-elliptic-curves-resource-usage.md
  kb/how-to/how_to_integrate_nv_seed.md
  kb/how-to/increasing_ssl_performance_and_tls_performance.md
  kb/how-to/reduce-polarssl-memory-and-storage-footprint.md
  kb/how-to/ssl_async.md
  kb/how-to/use-sni.md
  kb/how-to/using-static-memory-instead-of-the-heap.md
  kb/licensing/copyright-and-contributions.md
  reviews/review_guidelines.md
Labels: bug, needs-review, needs-reviewer, size-s, priority-medium

#46 Minor knowledge base updates for Mbed TLS 2.2x and 3.x
  kb/compiling-and-building/compile-mbedtls-to-a-static-library-in-eclipse-cdt.md
  kb/compiling-and-building/how-do-i-configure-mbedtls.md
  kb/compiling-and-building/mbedtls-failed-to-compile.md
  kb/compiling-and-building/using-mbedtls-in-microsoft-visual-studio-2015.md
  kb/cryptography/elliptic-curve-performance-nist-vs-brainpool.md
  kb/cryptography/providing-diffie-hellman-or-dhm-parameters.md
  kb/cryptography/rsa-key-pair-generator.md
  kb/cryptography/use-external-rsa-private-key.md
  kb/development/hw_acc_guidelines.md
  kb/development/mbedtls-coding-standards.md
  kb/development/restartable-ecc.md
  kb/development/sample_applications.md
  kb/development/test_suites.md
  kb/development/thread-safety-and-multi-threading.md
  kb/development/what-external-dependencies-does-mbedtls-rely-on.md
  kb/generic/abstraction-layers.md
  kb/generic/what-tests-and-checks-are-run-for-polarssl.md
  kb/how-to/add-a-random-generator.md
  kb/how-to/code-size.md
  kb/how-to/controlling_package_size.md
  kb/how-to/dtls-tutorial.md
  kb/how-to/encrypt-and-decrypt-with-rsa.md
  kb/how-to/generate-a-certificate-request-csr.md
  kb/how-to/generate-a-self-signed-certificate.md
  kb/how-to/generate-an-aes-key.md
  kb/how-to/how-do-i-port-mbed-tls-to-a-new-environment-OS.md
  kb/how-to/how-do-i-tune-elliptic-curves-resource-usage.md
  kb/how-to/how_to_integrate_nv_seed.md
  kb/how-to/increasing_ssl_performance_and_tls_performance.md
  kb/how-to/reduce-polarssl-memory-and-storage-footprint.md
  kb/how-to/ssl_async.md
  kb/how-to/use-sni.md
  kb/how-to/using-static-memory-instead-of-the-heap.md
Labels: enhancement, size-s
