Repository Mbed-TLS/mbedtls-docs, pull requests merged in 2022-09, with the labels that each got.

#48 Migrate tool version table to mbedtls-docs
  kb/development/tool-versions-lts-distributions.md
Labels: enhancement, size-s

#45 Do not use loose modules
  kb/how-to/using-loose-modules-without-the-full-library.md
Labels: needs-review, size-s

#50 Update licensing section of Knowledge Base to Apache 2.0 only
  kb/licensing/how-is-mbedtls-protected.md
  kb/licensing/using-mbedtls-in-a-non-apache-project.md
  kb/licensing/using-mbedtls-in-a-non-gpl-project.md
Labels: size-s, priority-medium

#53 Style guide syntax highlighting
  kb/development/mbedtls-coding-standards.md
Labels: needs-review, needs-reviewer, size-s
