Repository Mbed-TLS/mbedtls-docs, pull requests merged in 2022-10, with the labels that each got.

#54 Replace "precompiler" with "preprocessor" in docs
  kb/development/mbedtls-coding-standards.md
Labels: size-s

#55 Update documentation links
  README.md
  index.md
Labels: bug, needs-review, needs-reviewer, size-s

#56 Some guidance on writing unit tests
  kb/development/test_suites.md
Labels: size-s, priority-low

#58 Coding style: formatting of lists
  kb/development/mbedtls-coding-standards.md
Labels: enhancement, size-s

#60 Add link to PSA Crypto specification
  index.md
Labels: enhancement, needs-review, needs-reviewer, size-s, priority-medium
