Repository Mbed-TLS/mbedtls-docs, pull requests merged in 2023-01, with the labels that each got.

#67 Add roadmap.md to the toctree
  index.md
  roadmap.md
Labels: size-s, priority-medium, approved

#71 Rewrite a branch with the new coding style
  tools/bin/mbedtls-rewrite-branch-style
  tools/test/.gitignore
  tools/test/mbedtls-test-rewrite-branch-style
Labels: size-m, approved

#69 Document the new coding style
  kb/development/mbedtls-coding-standards.md
Labels: needs-review, needs-reviewer, size-s, priority-high, needs-preceding-pr

#70 Document the code style switch
  kb/how-to/rewrite-branch-for-coding-style.md
Labels: needs-review, size-s

#73 Branch rewrite script: minor improvements
  kb/how-to/rewrite-branch-for-coding-style.md
  tools/bin/mbedtls-rewrite-branch-style
  tools/test/mbedtls-test-rewrite-branch-style
Labels: bug, size-s, priority-high, approved

#75 Branch rewriting: ship it!
  kb/how-to/rewrite-branch-for-coding-style.md
  tools/bin/mbedtls-rewrite-branch-style
  tools/test/mbedtls-test-rewrite-branch-style
Labels: enhancement, needs-review, size-s

#74 Branch rewrite script: handle deleted files
  kb/how-to/rewrite-branch-for-coding-style.md
  tools/bin/mbedtls-rewrite-branch-style
  tools/test/mbedtls-test-rewrite-branch-style
Labels: enhancement, needs-review, size-s, priority-high

#76 Add tips on installing uncrustify
  kb/development/mbedtls-coding-standards.md
  kb/how-to/rewrite-branch-for-coding-style.md
  kb/how-to/uncrustify.md
Labels: enhancement, size-s, approved

#78 Add introductory section
  index.md
Labels: size-s, priority-medium, approved
